# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gpt_service_pb2 as gpt__service__pb2


class GPTServiceStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessText = channel.unary_unary(
                '/GPTService.GPTService/ProcessText',
                request_serializer=gpt__service__pb2.ProcessRequest.SerializeToString,
                response_deserializer=gpt__service__pb2.ProcessReply.FromString,
                )


class GPTServiceServicer(object):
    """The service definition.
    """

    def ProcessText(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GPTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessText': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessText,
                    request_deserializer=gpt__service__pb2.ProcessRequest.FromString,
                    response_serializer=gpt__service__pb2.ProcessReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GPTService.GPTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GPTService(object):
    """The service definition.
    """

    @staticmethod
    def ProcessText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GPTService.GPTService/ProcessText',
            gpt__service__pb2.ProcessRequest.SerializeToString,
            gpt__service__pb2.ProcessReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
